"""
Diagnostic Report - Data structures for session analysis

Contains classes for representing issues, evidence, and reports
generated by the PostSessionAnalyzer.
"""

import os
import json
import logging
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path

logger = logging.getLogger(__name__)


class IssueSeverity(Enum):
    """Severity levels for detected issues."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IssueType(Enum):
    """Types of issues that can be detected."""
    INTENT_MISCLASSIFICATION = "intent_misclassification"
    TOOL_FAILURE = "tool_failure"
    USER_FRUSTRATION = "user_frustration"
    EMPTY_RESPONSE = "empty_response"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


@dataclass
class Evidence:
    """Evidence supporting an issue detection."""
    description: str
    data: Dict[str, Any]
    timestamp: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "description": self.description,
            "data": self.data,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
        }


@dataclass
class ProposedFix:
    """A proposed fix for an identified issue."""
    description: str
    file_path: str
    line_number: Optional[int] = None
    code_snippet: Optional[str] = None
    confidence: float = 0.5

    def to_dict(self) -> Dict[str, Any]:
        return {
            "description": self.description,
            "file_path": self.file_path,
            "line_number": self.line_number,
            "code_snippet": self.code_snippet,
            "confidence": self.confidence,
        }


@dataclass
class Issue:
    """A detected issue from session analysis."""
    issue_type: IssueType
    severity: IssueSeverity
    title: str
    description: str
    evidence: List[Evidence] = field(default_factory=list)
    proposed_fixes: List[ProposedFix] = field(default_factory=list)
    frequency: int = 1  # How many times this issue occurred
    confidence: float = 0.5
    user_input: Optional[str] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "issue_type": self.issue_type.value,
            "severity": self.severity.value,
            "title": self.title,
            "description": self.description,
            "evidence": [e.to_dict() for e in self.evidence],
            "proposed_fixes": [f.to_dict() for f in self.proposed_fixes],
            "frequency": self.frequency,
            "confidence": self.confidence,
            "user_input": self.user_input,
            "expected_result": self.expected_result,
            "actual_result": self.actual_result,
        }

    def calculate_impact_score(self) -> float:
        """Calculate impact score based on severity, frequency, and confidence."""
        severity_weights = {
            IssueSeverity.LOW: 1.0,
            IssueSeverity.MEDIUM: 2.0,
            IssueSeverity.HIGH: 3.0,
            IssueSeverity.CRITICAL: 5.0,
        }
        severity_score = severity_weights.get(self.severity, 1.0)
        return severity_score * self.frequency * self.confidence


@dataclass
class SessionData:
    """Aggregated data from a voice session."""
    session_id: str
    start_time: datetime
    end_time: Optional[datetime] = None
    messages: List[Dict[str, Any]] = field(default_factory=list)
    intent_logs: List[Dict[str, Any]] = field(default_factory=list)
    tool_logs: List[Dict[str, Any]] = field(default_factory=list)
    agent_execution_logs: List[Dict[str, Any]] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def duration_seconds(self) -> float:
        if self.end_time and self.start_time:
            return (self.end_time - self.start_time).total_seconds()
        return 0.0

    @property
    def user_message_count(self) -> int:
        return sum(1 for m in self.messages if m.get("role") == "user")

    @property
    def assistant_message_count(self) -> int:
        return sum(1 for m in self.messages if m.get("role") == "assistant")


@dataclass
class DiagnosticReport:
    """Complete diagnostic report for a session."""
    session_id: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    duration_seconds: float = 0.0
    total_messages: int = 0
    user_messages: int = 0
    tools_called: int = 0
    errors_count: int = 0
    issues: List[Issue] = field(default_factory=list)
    top_issue: Optional[Issue] = None
    summary: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "session_id": self.session_id,
            "created_at": self.created_at.isoformat(),
            "duration_seconds": self.duration_seconds,
            "total_messages": self.total_messages,
            "user_messages": self.user_messages,
            "tools_called": self.tools_called,
            "errors_count": self.errors_count,
            "issues": [i.to_dict() for i in self.issues],
            "top_issue": self.top_issue.to_dict() if self.top_issue else None,
            "summary": self.summary,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, ensure_ascii=False)

    def to_markdown(self) -> str:
        """Generate a markdown report."""
        lines = [
            f"# Diagnostic Report: Session {self.session_id}",
            "",
            "## Session Overview",
            f"- **Created:** {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}",
            f"- **Duration:** {self.duration_seconds:.1f}s",
            f"- **Messages:** {self.user_messages} user, {self.total_messages - self.user_messages} assistant",
            f"- **Tools called:** {self.tools_called}",
            f"- **Errors:** {self.errors_count}",
            "",
        ]

        if self.summary:
            lines.extend(["## Summary", "", self.summary, ""])

        if self.top_issue:
            lines.extend(self._format_issue_markdown(self.top_issue, is_top=True))

        if len(self.issues) > 1:
            lines.extend(["", "## Other Issues Detected", ""])
            for issue in self.issues:
                if issue != self.top_issue:
                    lines.extend(self._format_issue_markdown(issue, is_top=False))

        if not self.issues:
            lines.extend(["", "## No Issues Detected", "", "The session completed without significant problems."])

        return "\n".join(lines)

    def _format_issue_markdown(self, issue: Issue, is_top: bool = False) -> List[str]:
        """Format an issue as markdown."""
        header_prefix = "## Top Issue Identified" if is_top else "###"
        lines = [
            "",
            f"{header_prefix}",
            "",
            f"### {issue.title}",
            "",
            f"**Type:** {issue.issue_type.value}",
            f"**Severity:** {issue.severity.value.upper()}",
            f"**Frequency:** {issue.frequency} occurrence(s)",
            f"**Confidence:** {issue.confidence:.0%}",
            "",
            "**Description:**",
            issue.description,
            "",
        ]

        if issue.user_input:
            lines.extend([
                "**User Input:**",
                f"```",
                issue.user_input,
                "```",
                "",
            ])

        if issue.actual_result and issue.expected_result:
            lines.extend([
                "**Actual Result:** " + issue.actual_result,
                "**Expected Result:** " + issue.expected_result,
                "",
            ])

        if issue.evidence:
            lines.append("**Evidence:**")
            for i, evidence in enumerate(issue.evidence, 1):
                lines.append(f"{i}. {evidence.description}")
            lines.append("")

        if issue.proposed_fixes:
            lines.append("**Proposed Fix(es):**")
            for fix in issue.proposed_fixes:
                lines.append(f"- {fix.description}")
                if fix.file_path:
                    file_ref = f"[{Path(fix.file_path).name}"
                    if fix.line_number:
                        file_ref += f":{fix.line_number}"
                    file_ref += f"]({fix.file_path}"
                    if fix.line_number:
                        file_ref += f"#L{fix.line_number}"
                    file_ref += ")"
                    lines.append(f"  - File: {file_ref}")
                if fix.code_snippet:
                    lines.append(f"  ```python\n  {fix.code_snippet}\n  ```")
            lines.append("")

        return lines

    def save(self, path: str) -> None:
        """Save the report to a file."""
        Path(path).parent.mkdir(parents=True, exist_ok=True)

        if path.endswith(".json"):
            with open(path, "w", encoding="utf-8") as f:
                f.write(self.to_json())
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(self.to_markdown())

        logger.info(f"[DiagnosticReport] Saved report to {path}")


def get_diagnostic_report_path(session_id: str) -> str:
    """Get the path for a diagnostic report file."""
    base_path = os.getenv("DIAGNOSTIC_REPORT_PATH", "diagnostic_reports")
    return os.path.join(base_path, f"{session_id}.md")


__all__ = [
    "IssueSeverity",
    "IssueType",
    "Evidence",
    "ProposedFix",
    "Issue",
    "SessionData",
    "DiagnosticReport",
    "get_diagnostic_report_path",
]
