"""
IntentAnalysisTeam - Parallel intent analysis through multiple agents

Phase 13: Multi-Agent Intent Analysis System

Coordinates multiple specialized agents to analyze user intent:
- ReasoningAgent: Multi-step logical reasoning
- ContextAgent: User context and history analysis
- HistoryAgent: Pattern detection from conversation history

Returns ranked hypotheses with confidence scores.
"""

import asyncio
import logging
import os
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional

# Load .env file if present
try:
    from dotenv import load_dotenv
    # Look for .env in project root
    env_path = os.path.join(os.path.dirname(__file__), '..', '..', '..', '.env')
    if os.path.exists(env_path):
        load_dotenv(env_path)
except ImportError:
    pass  # dotenv not installed, rely on environment

from swarm.analysis.user_context import UserContext

logger = logging.getLogger(__name__)


@dataclass
class IntentHypothesis:
    """
    A single hypothesis about user intent.

    Generated by analysis agents with confidence scores
    and reasoning explanations.
    """
    event_type: str
    payload: Dict[str, Any]
    confidence: float  # 0.0 - 1.0
    reasoning: str  # Explanation why this hypothesis
    source: str  # "reasoning" | "context" | "history"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "event_type": self.event_type,
            "payload": self.payload,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "source": self.source,
        }


class IntentAnalysisTeam:
    """
    Parallel Intent Analysis through multiple specialized agents.

    Coordinates:
    - ReasoningAgent: Logical multi-step analysis
    - ContextAgent: User context aware analysis
    - HistoryAgent: Pattern-based analysis from history

    Returns merged and ranked hypotheses.
    """

    def __init__(self, model: Optional[str] = None):
        """
        Initialize the analysis team.

        Args:
            model: LLM model to use (default: from env or Claude Haiku)
        """
        self._model = model or os.getenv("ANALYSIS_MODEL", "anthropic/claude-3.5-haiku")
        self._client = None
        self._reasoning_agent = None
        self._context_agent = None

    @property
    def client(self):
        """Lazy-load OpenAI client (AutoGen clients are not compatible with direct API calls)."""
        if self._client is None:
            try:
                from openai import OpenAI
                api_key = os.getenv("OPENROUTER_API_KEY")
                if not api_key:
                    raise ValueError("OPENROUTER_API_KEY not set")

                self._client = OpenAI(
                    api_key=api_key,
                    base_url="https://openrouter.ai/api/v1"
                )
                logger.info(f"IntentAnalysisTeam using OpenRouter: {self._model}")
            except Exception as e:
                logger.error(f"Failed to create analysis client: {e}")
                raise
        return self._client

    async def analyze(self, user_input: str, context: UserContext, audio_input: Optional["AudioMetadataInput"] = None) -> List[IntentHypothesis]:
        """
        Analyze user input with multiple agents in parallel.

        Args:
            user_input: Natural language user request
            context: User context from UserContextBuilder
            audio_input: Optional audio metadata for enhanced analysis

        Returns:
            List of IntentHypothesis sorted by confidence (highest first)
        """
        logger.debug(f"Analyzing intent: '{user_input[:50]}...'")

        # Start parallel analysis
        tasks = [
            self._reasoning_analysis(user_input),
            self._context_analysis(user_input, context),
            self._history_analysis(user_input, context),
            self._semantic_analysis(user_input, context, audio_input),
        ]

        # Wait for all results (parallel)
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Collect hypotheses, handling errors
        hypotheses: List[IntentHypothesis] = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                logger.warning(f"Analysis task {i} failed: {result}")
                continue
            if isinstance(result, list):
                hypotheses.extend(result)
            elif isinstance(result, IntentHypothesis):
                hypotheses.append(result)

        # Merge and deduplicate
        merged = self._merge_hypotheses(hypotheses)

        # Sort by confidence (highest first)
        sorted_hypotheses = sorted(merged, key=lambda h: h.confidence, reverse=True)

        logger.info(f"Analysis complete: {len(sorted_hypotheses)} hypotheses")
        for h in sorted_hypotheses[:3]:
            logger.debug(f"  {h.event_type} ({h.confidence:.0%}) - {h.source}")

        return sorted_hypotheses

    async def _reasoning_analysis(self, user_input: str) -> List[IntentHypothesis]:
        """
        Multi-step reasoning analysis.

        Analyzes the logical structure of the request
        to determine the most likely intent.
        """
        try:
            from swarm.analysis.reasoning_agent import ReasoningAgent

            if self._reasoning_agent is None:
                self._reasoning_agent = ReasoningAgent(self.client, self._model)

            return await self._reasoning_agent.analyze(user_input)
        except ImportError:
            logger.debug("ReasoningAgent not available, using fallback")
            return await self._fallback_reasoning(user_input)
        except Exception as e:
            logger.warning(f"Reasoning analysis failed: {e}")
            return []

    async def _context_analysis(self, user_input: str, context: UserContext) -> List[IntentHypothesis]:
        """
        Context-aware analysis.

        Uses user context (recent actions, preferences, current space)
        to refine intent understanding.
        """
        try:
            from swarm.analysis.context_agent import ContextAgent

            if self._context_agent is None:
                self._context_agent = ContextAgent(self.client, self._model)

            return await self._context_agent.analyze(user_input, context)
        except ImportError:
            logger.debug("ContextAgent not available, using fallback")
            return await self._fallback_context(user_input, context)
        except Exception as e:
            logger.warning(f"Context analysis failed: {e}")
            return []

    async def _history_analysis(self, user_input: str, context: UserContext) -> List[IntentHypothesis]:
        """
        History-based pattern analysis.

        Looks for patterns in recent actions to predict likely intent.
        This is a lightweight analysis that doesn't require LLM.
        """
        hypotheses = []

        # Check for continuation patterns
        recent_types = context.get_recent_event_types()

        if not recent_types:
            return hypotheses

        # Pattern: Just created an idea, might want to connect it
        if "idea.create" in recent_types[-3:]:
            if any(word in user_input.lower() for word in ["verbind", "verlink", "mit"]):
                hypotheses.append(IntentHypothesis(
                    event_type="idea.connect",
                    payload={},  # Will be filled by other analyzers
                    confidence=0.6,
                    reasoning="User recently created an idea and mentions connecting",
                    source="history"
                ))

        # Pattern: Just entered a space, might want to list ideas
        if "bubble.enter" in recent_types[-2:]:
            if any(word in user_input.lower() for word in ["was", "zeig", "list", "ideen"]):
                hypotheses.append(IntentHypothesis(
                    event_type="idea.list",
                    payload={},
                    confidence=0.7,
                    reasoning="User just entered a space and asks about content",
                    source="history"
                ))

        # Pattern: Multiple create operations, might be in batch mode
        create_count = sum(1 for t in recent_types[-5:] if "create" in t)
        if create_count >= 2:
            if any(word in user_input.lower() for word in ["noch", "weitere", "mehr"]):
                # Likely continuing the same type of creation
                last_create = next((t for t in reversed(recent_types) if "create" in t), None)
                if last_create:
                    hypotheses.append(IntentHypothesis(
                        event_type=last_create,
                        payload={},
                        confidence=0.5,
                        reasoning="User is in batch creation mode",
                        source="history"
                    ))

        return hypotheses

    async def _semantic_analysis(self, user_input: str, context: UserContext, audio_input: Optional["AudioMetadataInput"] = None) -> List[IntentHypothesis]:
        """
        Semantic analysis with audio metadata integration.

        Uses transcript metadata and NLP analysis for enhanced intent detection.
        """
        try:
            from swarm.analysis.semantic_agent import get_semantic_agent

            semantic_agent = get_semantic_agent()
            return await semantic_agent.analyze(user_input, context, audio_input)
        except ImportError:
            logger.debug("SemanticAgent not available")
            return []
        except Exception as e:
            logger.warning(f"Semantic analysis failed: {e}")
            return []

    async def _fallback_reasoning(self, user_input: str) -> List[IntentHypothesis]:
        """Fallback reasoning without ReasoningAgent."""
        # Use direct LLM call with simplified prompt
        prompt = f"""Analysiere den User Intent und gib den wahrscheinlichsten Event-Type zurueck.

Verfuegbare Event Types:
- bubble.list, bubble.create, bubble.enter, bubble.exit, bubble.delete
- idea.list, idea.create, idea.find, idea.update, idea.delete
- idea.connect: Zwei SPEZIFISCHE Ideen verbinden (wenn User Idee1 + Idee2 nennt)
- idea.auto_link: ALLE Ideen automatisch verlinken (wenn User "verlinke die Ideen" sagt, ohne spezifische Namen)
- idea.analyze_links: Verlinkungsvorschlaege analysieren
- idea.summarize, idea.whitepaper: Zusammenfassung/Whitepaper erstellen
- desktop.open_app, desktop.click, desktop.type, desktop.task
- code.generate, code.modify, code.status
- conversation.greeting, conversation.help, conversation.unknown

WICHTIG: Wenn User "verlinke die Ideen" oder "verbinde Ideen sinnvoll" sagt OHNE spezifische Namen zu nennen,
ist das IMMER idea.auto_link (NICHT bubble.enter oder idea.connect)!

User Input: {user_input}

Antworte NUR mit JSON:
{{"event_type": "...", "confidence": 0.0-1.0, "reasoning": "..."}}"""

        try:
            response = self.client.chat.completions.create(
                model=self._model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=200,
            )

            import json
            content = response.choices[0].message.content.strip()

            # Extract JSON
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()

            result = json.loads(content)

            return [IntentHypothesis(
                event_type=result.get("event_type", "conversation.unknown"),
                payload={},
                confidence=float(result.get("confidence", 0.5)),
                reasoning=result.get("reasoning", "Fallback reasoning"),
                source="reasoning"
            )]
        except Exception as e:
            logger.warning(f"Fallback reasoning failed: {e}")
            return []

    async def _fallback_context(self, user_input: str, context: UserContext) -> List[IntentHypothesis]:
        """Fallback context analysis without ContextAgent."""
        hypotheses = []

        # Use context to boost certain hypotheses
        if context.current_space:
            # If in a space, idea operations are more likely
            if any(word in user_input.lower() for word in ["idee", "notiz", "erstell"]):
                hypotheses.append(IntentHypothesis(
                    event_type="idea.create",
                    payload={},
                    confidence=0.6,
                    reasoning=f"User is in space '{context.current_space}' and mentions creating",
                    source="context"
                ))

        # Check if user mentions recently discussed entities
        for entity in context.mentioned_entities:
            if entity.lower() in user_input.lower():
                hypotheses.append(IntentHypothesis(
                    event_type="idea.find",
                    payload={"query": entity},
                    confidence=0.5,
                    reasoning=f"User mentions previously discussed entity '{entity}'",
                    source="context"
                ))
                break

        return hypotheses

    def _merge_hypotheses(self, hypotheses: List[IntentHypothesis]) -> List[IntentHypothesis]:
        """
        Merge and deduplicate hypotheses from multiple agents.

        Same event_type from different sources gets confidence boost.
        """
        if not hypotheses:
            return []

        # Group by event_type
        grouped: Dict[str, List[IntentHypothesis]] = {}
        for h in hypotheses:
            if h.event_type not in grouped:
                grouped[h.event_type] = []
            grouped[h.event_type].append(h)

        # Merge each group
        merged = []
        for event_type, group in grouped.items():
            if len(group) == 1:
                merged.append(group[0])
            else:
                # Multiple sources agree - boost confidence
                avg_confidence = sum(h.confidence for h in group) / len(group)
                boost = min(0.2, 0.1 * (len(group) - 1))  # Up to 0.2 boost
                final_confidence = min(1.0, avg_confidence + boost)

                # Combine payloads
                combined_payload = {}
                for h in group:
                    combined_payload.update(h.payload)

                # Combine reasoning
                sources = set(h.source for h in group)
                combined_reasoning = f"Multiple sources ({', '.join(sources)}) agree: " + group[0].reasoning

                merged.append(IntentHypothesis(
                    event_type=event_type,
                    payload=combined_payload,
                    confidence=final_confidence,
                    reasoning=combined_reasoning,
                    source="+".join(sorted(sources))
                ))

        return merged

    def select_best(self, hypotheses: List[IntentHypothesis], threshold: float = 0.5) -> Optional[IntentHypothesis]:
        """
        Select the best hypothesis if confidence exceeds threshold.

        Args:
            hypotheses: Sorted list of hypotheses
            threshold: Minimum confidence to accept

        Returns:
            Best hypothesis or None if all below threshold
        """
        if not hypotheses:
            return None

        best = hypotheses[0]
        if best.confidence >= threshold:
            return best

        logger.info(f"Best hypothesis ({best.event_type}) below threshold: {best.confidence:.0%} < {threshold:.0%}")
        return None


# Singleton
_analysis_team: Optional[IntentAnalysisTeam] = None


def get_intent_analysis_team() -> IntentAnalysisTeam:
    """Get or create IntentAnalysisTeam singleton."""
    global _analysis_team
    if _analysis_team is None:
        _analysis_team = IntentAnalysisTeam()
    return _analysis_team


__all__ = [
    "IntentHypothesis",
    "IntentAnalysisTeam",
    "get_intent_analysis_team",
]
